version: '3'
services: 
  db_basketball:
    image: postgres:13.3-alpine
    restart: always
    container_name: db_basketball
    env_file: 
      - .env
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - basketball_db_data:/var/lib/postgresql/data  

volumes: 
  basketball_db_data:
